version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        command: >
            gunicorn -b 0.0.0.0:5000 --name radiosonde --reload "radiosonde.wsgi:app"
        volumes:
            - '.:/app'
        env_file:
            - '.env'
        depends_on:
            - postgres

    postgres:
        image: 'postgres:9.5'
        env_file:
            - '.env'
        volumes:
            - 'postgres_pl:/var/lib/postgresql/data'
        ports:
            - '5432:5432'

    nginx:
        build: ./nginx/
        restart: always
        ports:
           - "80:80"
        volumes:
           - /www/static
        links:
            - web
        depends_on:
            - web

volumes:
  postgres_pl: